# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-06 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_myurlshortner_shortcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myurlshortner',
            name='shortcode',
        ),
    ]
