# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-06 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20181206_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurlshortner',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
