# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20181206_2240'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myurlshortner',
            managers=[
                ('random_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='myurlshortner',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
