# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20181206_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurlshortner',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
