# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-06 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_auto_20181207_0001'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myurlshortner',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='myurlshortner',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
